import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import type { ScriptOutput } from "../types.js";

// __dirname equivalent for ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export interface GenerateProjectInput {
  script: ScriptOutput;
  outputDir: string;
  images?: Record<string, string>;
  showSubtitles?: boolean;
}

export interface GenerateProjectOutput {
  projectDir: string;
  entryPoint: string;
  compositionId: string;
}

export async function generateProject(
  input: GenerateProjectInput,
): Promise<GenerateProjectOutput> {
  const { script, outputDir, images = {}, showSubtitles = false } = input;

  // Resolve paths to shared packages
  // At runtime: __dirname = packages/renderer/dist/utils/
  // So rendererDir = packages/renderer/dist/ → we want packages/renderer/
  // Use src layout path: __dirname in src = packages/renderer/src/utils/
  const rendererDir = path.resolve(__dirname, "../../.."); // packages/renderer
  const typesDir = path.resolve(rendererDir, "../types"); // packages/types (if exists)
  const hasTypes = fs.existsSync(typesDir);

  const compositionId = "Video"; // always landscape for now

  // 1. Scaffold directory structure
  fs.mkdirSync(path.join(outputDir, "src"), { recursive: true });
  fs.mkdirSync(path.join(outputDir, "out"), { recursive: true });

  // 2. Write package.json with file: protocol
  const packageJson: Record<string, unknown> = {
    name: `video-${slugify(script.title)}`,
    version: "1.0.0",
    private: true,
    dependencies: {
      "@video-script/renderer": `file:${rendererDir}`,
      ...(hasTypes ? { "@video-script/types": `file:${typesDir}` } : {}),
      remotion: "4.0.436",
      "@remotion/bundler": "4.0.436",
      "@remotion/renderer": "4.0.436",
      "@remotion/transitions": "4.0.436",
    },
  };
  fs.writeFileSync(
    path.join(outputDir, "package.json"),
    JSON.stringify(packageJson, null, 2),
  );

  // 3. Write tsconfig.json
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "ES2022",
      moduleResolution: "bundler",
      jsx: "react-jsx",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: "dist",
    },
    include: ["src"],
  };
  fs.writeFileSync(
    path.join(outputDir, "tsconfig.json"),
    JSON.stringify(tsconfig, null, 2),
  );

  // 4. Write src/index.ts (Remotion entry point)
  const indexContent = `import { registerRoot } from 'remotion';
import { RemotionRoot } from './Root.js';

registerRoot(RemotionRoot);
`;
  fs.writeFileSync(path.join(outputDir, "src", "index.ts"), indexContent);

  // 5. Write src/Root.tsx (embeds script data as defaultProps)
  const rootContent = generateRootTsx({
    script,
    images,
    showSubtitles,
    compositionId,
  });
  fs.writeFileSync(path.join(outputDir, "src", "Root.tsx"), rootContent);

  // 6. Write .gitignore
  fs.writeFileSync(
    path.join(outputDir, ".gitignore"),
    "node_modules/\ndist/\nout/\n",
  );

  // 7. Write README.md
  fs.writeFileSync(
    path.join(outputDir, "README.md"),
    `# ${script.title}\n\nGenerated by video-script.\n\nPreview: \`npx remotion studio\`\n`,
  );

  // 8. Run npm install to resolve file: symlinks
  execSync("npm install --legacy-peer-deps", {
    cwd: outputDir,
    stdio: "inherit",
  });

  return {
    projectDir: outputDir,
    entryPoint: path.join(outputDir, "src", "index.ts"),
    compositionId,
  };
}

function generateRootTsx(opts: {
  script: ScriptOutput;
  images: Record<string, string>;
  showSubtitles: boolean;
  compositionId: string;
}): string {
  const { script, images, showSubtitles, compositionId } = opts;
  const totalFrames = Math.ceil(script.totalDuration * 30);
  const propsJson = JSON.stringify({ script, images, showSubtitles }, null, 2);

  return `import { Composition } from 'remotion';
import { VideoComposition } from '@video-script/renderer';
import type { VideoCompositionProps } from '@video-script/renderer';

const defaultProps: VideoCompositionProps = ${propsJson};

export const RemotionRoot = () => (
  <Composition
    id="${compositionId}"
    component={VideoComposition}
    durationInFrames={${totalFrames}}
    fps={30}
    width={1920}
    height={1080}
    defaultProps={defaultProps}
  />
);
`;
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}
